name: Release

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir dist
          GOOS=linux   GOARCH=amd64 go build -o dist/app-linux-amd64 .
          GOOS=darwin  GOARCH=amd64 go build -o dist/app-darwin-amd64 .
          GOOS=windows GOARCH=amd64 go build -o dist/app-windows-amd64.exe .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/app-linux-amd64
            dist/app-darwin-amd64
            dist/app-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
